#!/bin/sh
# List the changes in a commit or in a block of consecutive commits


usage()
{
    myself=${0##*/}
    cat >&2 <<END_OF_USAGE
Usage:
  For a single commit:
    $myself commit-id [affected files]
  For a block of several consecutive commits:
    $myself -b start-commit-id end-commit-id [affected files]
  For the latest commit in the current branch:
    $myself -l [affected files]
END_OF_USAGE
    
    exit 1
}

case "$1" in
    '-b')
        start_commit=$2
        end_commit=$3
        [ "$end_commit" ] || usage
        shift 3
        ;;
    '-l')
        start_commit=$(git log | head -n1 | awk '{print $2}')
        if ! [ "$start_commit" ]; then
            echo >&2 "Cannot find any commits!"
            exit 1
        fi
        end_commit=$start_commit
        shift
        ;;
    *)
        start_commit=$1
        [ "$start_commit" ] || usage
        end_commit=$start_commit
        shift
esac

git diff "$start_commit"~ "$end_commit" "$@"
